# -*- coding: utf-8 -*-
"""Another copy of Matrix Factorization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tmgn_eG9jaPJ2-bAb8KLAnzj3e12UVwW
"""

!pip install implicit scipy numpy pandas

# --- CONFIGURATION ---
FILENAME = "train-1.txt"
OUTPUT_FILE = "tin_recommendations_final.txt"
FACTORS_TO_TEST = [20, 50, 100, 200]
REG_TO_TEST = [0.01, 0.1, 1, 10]
K = 20             # Top-K for evaluation
NUM_NEGATIVES = 99 # For Sampled Evaluation (1 vs 99)

import numpy as np
import scipy.sparse as sparse
import implicit
import random
import time
import pandas as pd

class MatrixFactorizationRunner:
    def __init__(self, file_path):
        self.file_path = file_path
        self.train_matrix = None
        self.user_map = {}
        self.item_map = {}
        self.inv_item_map = {}
        self.unique_users = []
        self.unique_items = []
        self.test_set = []
        self.user_seen_items = {}

    def load_data(self):
        print(f"Loading {self.file_path}...")
        with open(self.file_path, 'r') as f:
            lines = f.readlines()

        raw_users = []
        raw_items = set()
        parsed_data = []

        for line in lines:
            parts = list(map(int, line.strip().split()))
            if len(parts) < 2: continue
            u_id, items = parts[0], parts[1:]

            raw_users.append(u_id)
            raw_items.update(items)
            parsed_data.append((u_id, items))

        self.unique_users = sorted(list(set(raw_users)))
        self.unique_items = sorted(list(raw_items))

        self.user_map = {u: i for i, u in enumerate(self.unique_users)}
        self.item_map = {item: i for i, item in enumerate(self.unique_items)}
        self.inv_item_map = {i: item for item, i in self.item_map.items()}

        return parsed_data

    def prepare_experiments(self):
        parsed_data = self.load_data()

        train_rows, train_cols, train_data = [], [], []
        self.user_seen_items = {u: set() for u in range(len(self.unique_users))}

        for u_id, items in parsed_data:
            u_idx = self.user_map[u_id]

            if len(items) >= 2:
                train_items = items[:-1]
                test_item = items[-1]

                if test_item in self.item_map:
                    self.test_set.append((u_idx, self.item_map[test_item]))
            else:
                train_items = items

            for i_id in train_items:
                if i_id in self.item_map:
                    i_idx = self.item_map[i_id]
                    train_rows.append(u_idx)
                    train_cols.append(i_idx)
                    train_data.append(1)
                    self.user_seen_items[u_idx].add(i_idx)

        self.train_matrix = sparse.csr_matrix((train_data, (train_rows, train_cols)),
                                             shape=(len(self.unique_users), len(self.unique_items)))
        print(f"Data Ready: {len(self.unique_users)} Users, {len(self.test_set)} Test Cases.")

    def get_negative_samples(self, u_idx):
        negatives = []
        seen = self.user_seen_items[u_idx]
        num_items = len(self.unique_items)
        negatives_set = set()

        while len(negatives) < NUM_NEGATIVES:
            neg = random.randint(0, num_items - 1)
            if neg not in seen and neg not in negatives_set:
                if u_idx < len(self.test_set) and neg == self.test_set[u_idx][1]:
                    continue
                negatives.append(neg)
                negatives_set.add(neg)
        return negatives

    def evaluate(self, model):
        if hasattr(model, 'to_cpu'): model = model.to_cpu()

        user_factors = model.user_factors
        item_factors = model.item_factors

        ndcg_sum = 0.0

        for u_idx, test_item_idx in self.test_set:
            negatives = self.get_negative_samples(u_idx)
            candidates = [test_item_idx] + negatives

            u_vec = user_factors[u_idx]
            cand_vecs = item_factors[candidates]
            scores = cand_vecs.dot(u_vec)

            ranked_indices = np.argsort(-scores)
            rank = np.where(ranked_indices == 0)[0][0]

            if rank < K:
                ndcg_sum += 1.0 / np.log2(rank + 2)

        return ndcg_sum / len(self.test_set)

runner = MatrixFactorizationRunner(FILENAME)
runner.prepare_experiments()

best_score = -1
best_params = {}

print("--- Experiment 1: Latent Factors (Fixed Reg=0.1) ---")
for f in FACTORS_TO_TEST:
    print(f"Training Factors={f} ... ", end="")
    model = implicit.als.AlternatingLeastSquares(factors=f, regularization=0.1, iterations=15, random_state=42)
    model.fit(runner.train_matrix, show_progress=False)
    score = runner.evaluate(model)
    print(f"NDCG@20: {score:.4f}")

    if score > best_score:
        best_score = score
        best_params = {'factors': f, 'regularization': 0.1}

best_f = best_params['factors']
print(f"\n--- Experiment 2: Regularization (Fixed Factors={best_f}) ---")
for r in REG_TO_TEST:
    if r == 0.1: continue
    print(f"Training Reg={r} ... ", end="")
    model = implicit.als.AlternatingLeastSquares(factors=best_f, regularization=r, iterations=15, random_state=42)
    model.fit(runner.train_matrix, show_progress=False)
    score = runner.evaluate(model)
    print(f"NDCG@20: {score:.4f}")

    if score > best_score:
        best_score = score
        best_params = {'factors': best_f, 'regularization': r}

print("\nWINNING PARAMETERS:", best_params)
print(f"BEST SCORE: {best_score:.4f}")

print(f"Retraining FINAL MODEL with {best_params} on full data...")

parsed_data = runner.load_data()
rows, cols, data = [], [], []
for u_id, items in parsed_data:
    u_idx = runner.user_map[u_id]
    for i_id in items:
        if i_id in runner.item_map:
            rows.append(u_idx)
            cols.append(runner.item_map[i_id])
            data.append(1)

full_matrix = sparse.csr_matrix((data, (rows, cols)),
                               shape=(len(runner.unique_users), len(runner.unique_items)))

model = implicit.als.AlternatingLeastSquares(**best_params, iterations=15, random_state=42)
model.fit(full_matrix, show_progress=True)

print(f"Generating recommendations to {OUTPUT_FILE}...")
with open(OUTPUT_FILE, 'w') as f:
    for u_id in runner.unique_users:
        u_idx = runner.user_map[u_id]
        ids, _ = model.recommend(u_idx, full_matrix[u_idx], N=20, filter_already_liked_items=True)
        rec_items = [str(runner.inv_item_map[i]) for i in ids]
        f.write(f"{u_id} " + " ".join(rec_items) + "\n")
print("Done.")

